FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "OrderDispatcher.EngagementService.API/OrderDispatcher.EngagementService.API.csproj"
RUN dotnet publish "OrderDispatcher.EngagementService.API/OrderDispatcher.EngagementService.API.csproj" -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ENTRYPOINT ["dotnet", "OrderDispatcher.EngagementService.API.dll"]
